#############################################################################
## Crytek Source File
## Copyright (C) 2013, Crytek Studios
##
## Creator: Christopher Bolte
## Date: Oct 31, 2013
## Description: WAF  based build system
#############################################################################

def build(bld):
	bld.CryFileContainer(
		target		= 'CryAudioCommon',
		vs_filter	= 'CryEngine/Audio',
		file_list	= 'audiocommon.waf_files',
	)
