// CryEngine Source File.
// Copyright (C), Crytek, 1999-2014.

#include "stdafx.h"
#include "Common_wwise.h"
// NOTE: Link only what you need and use!!

// Win32 or Win64 (Note: for WIN64 WIN32 is automatically defined as well!)
//////////////////////////////////////////////////////////////////////////
#if (defined(WIN32) || defined(WIN64)) && (!defined(XENON) && !defined(PS3) && !defined(DURANGO) && !defined(ORBIS) && !defined(MAC) && !defined(LINUX))

#if defined(WIN32) && !defined(WIN64)
#pragma message ("*** Win32 ***")
#elif defined(WIN32) && defined(WIN64)
#pragma message ("*** Win64 ***")
#endif // (Win32 && !Win64) || (Win32 && Win64)

#if defined(WWISE_FOR_DEBUG) || defined(WWISE_FOR_PROFILE) || defined(WWISE_FOR_RELEASE)
// Core modules
#		pragma message ("***WWISE linking against: AkMemoryMgr.lib")
#		pragma comment(lib,"AkMemoryMgr.lib")
#		pragma message ("***WWISE linking against: AkMusicEngine.lib")
#		pragma comment(lib,"AkMusicEngine.lib")
#		pragma message ("***WWISE linking against: AkSoundEngine.lib")
#		pragma comment(lib,"AkSoundEngine.lib")
#		pragma message ("***WWISE linking against: AkStreamMgr.lib")
#		pragma comment(lib,"AkStreamMgr.lib")
#		pragma message ("***WWISE linking against: dxguid.lib")
#		pragma comment(lib, "dxguid.lib")
#		pragma message ("***WWISE linking against: ws2_32.lib")
#		pragma comment(lib, "ws2_32.lib")
#		pragma message ("***WWISE linking against: Dsound.lib")
#		pragma comment(lib, "Dsound.lib")
#		pragma message ("***WWISE linking against: XInput.lib")
#		pragma comment(lib, "XInput.lib")
#		pragma message ("***WWISE linking against: Msacm32.lib")
#		pragma comment(lib, "Msacm32.lib")
#if !defined(WWISE_FOR_RELEASE)
// Does not exist for Release builds!
#		pragma message ("***WWISE linking against: CommunicationCentral.lib")
#		pragma comment(lib, "CommunicationCentral.lib")
// SoundFrame is disabled in Release builds
#		pragma message ("***WWISE linking against: SFlib.lib")
#		pragma comment(lib, "SFlib.lib")
#endif // !WWISE_FOR_RELEASE

// Plug-ins
#		pragma message ("***WWISE linking against: AkConvolutionReverbFX.lib")
#		pragma comment(lib, "AkConvolutionReverbFX.lib")
#		pragma message ("***WWISE linking against: iZTrashMultibandDistortionFX.lib")
#		pragma comment(lib, "iZTrashMultibandDistortionFX.lib")
#		pragma message ("***WWISE linking against: AstoundsoundExpanderFX.lib")
#		pragma comment(lib, "AstoundsoundExpanderFX.lib")
#		pragma message ("***WWISE linking against: AkTremoloFX.lib")
#		pragma comment(lib, "AkTremoloFX.lib")
#		pragma message ("***WWISE linking against: AkMotionGenerator.lib")
#		pragma comment(lib, "AkMotionGenerator.lib")
#		pragma message ("***WWISE linking against: AkSineSource.lib")
#		pragma comment(lib, "AkSineSource.lib")
#		pragma message ("***WWISE linking against: AkSoundSeedWind.lib")
#		pragma comment(lib, "AkSoundSeedWind.lib")
#		pragma message ("***WWISE linking against: AkStereoDelayFX.lib")
#		pragma comment(lib, "AkStereoDelayFX.lib")
#		pragma message ("***WWISE linking against: AkGuitarDistortionFX.lib")
#		pragma comment(lib, "AkGuitarDistortionFX.lib")
#		pragma message ("***WWISE linking against: AkRumble.lib")
#		pragma comment(lib, "AkRumble.lib")
#		pragma message ("***WWISE linking against: AkMP3Source.lib")
#		pragma comment(lib, "AkMP3Source.lib")
#		pragma message ("***WWISE linking against: iZTrashBoxModelerFX.lib")
#		pragma comment(lib, "iZTrashBoxModelerFX.lib")
#		pragma message ("***WWISE linking against: AkSoundSeedImpactFX.lib")
#		pragma comment(lib, "AkSoundSeedImpactFX.lib")
#		pragma message ("***WWISE linking against: AkRoomVerbFX.lib")
#		pragma comment(lib, "AkRoomVerbFX.lib")
#		pragma message ("***WWISE linking against: iZTrashDelayFX.lib")
#		pragma comment(lib, "iZTrashDelayFX.lib")
#		pragma message ("***WWISE linking against: McDSPFutzBoxFX.lib")
#		pragma comment(lib, "McDSPFutzBoxFX.lib")
#		pragma message ("***WWISE linking against: AkParametricEQFX.lib")
#		pragma comment(lib, "AkParametricEQFX.lib")
#		pragma message ("***WWISE linking against: McDSPLimiterFX.lib")
#		pragma comment(lib, "McDSPLimiterFX.lib")
#		pragma message ("***WWISE linking against: AkToneSource.lib")
#		pragma comment(lib, "AkToneSource.lib")
#		pragma message ("***WWISE linking against: AkFlangerFX.lib")
#		pragma comment(lib, "AkFlangerFX.lib")
#		pragma message ("***WWISE linking against: AkCompressorFX.lib")
#		pragma comment(lib, "AkCompressorFX.lib")
#		pragma message ("***WWISE linking against: AstoundsoundFolddownFX.lib")
#		pragma comment(lib, "AstoundsoundFolddownFX.lib")
#		pragma message ("***WWISE linking against: AkAudioInputSource.lib")
#		pragma comment(lib, "AkAudioInputSource.lib")
#		pragma message ("***WWISE linking against: AkDelayFX.lib")
#		pragma comment(lib, "AkDelayFX.lib")
#		pragma message ("***WWISE linking against: CrankcaseAudioREVModelPlayerFX.lib")
#		pragma comment(lib, "CrankcaseAudioREVModelPlayerFX.lib")
#		pragma message ("***WWISE linking against: AkSoundSeedWoosh.lib")
#		pragma comment(lib, "AkSoundSeedWoosh.lib")
#		pragma message ("***WWISE linking against: iZHybridReverbFX.lib")
#		pragma comment(lib, "iZHybridReverbFX.lib")
#		pragma message ("***WWISE linking against: AkPitchShifterFX.lib")
#		pragma comment(lib, "AkPitchShifterFX.lib")
#		pragma message ("***WWISE linking against: iZTrashDynamicsFX.lib")
#		pragma comment(lib, "iZTrashDynamicsFX.lib")
#		pragma message ("***WWISE linking against: iZTrashDistortionFX.lib")
#		pragma comment(lib, "iZTrashDistortionFX.lib")
#		pragma message ("***WWISE linking against: AstoundsoundRTIFX.lib")
#		pragma comment(lib, "AstoundsoundRTIFX.lib")
#		pragma message ("***WWISE linking against: AkSilenceSource.lib")
#		pragma comment(lib, "AkSilenceSource.lib")
#		pragma message ("***WWISE linking against: AkGainFX.lib")
#		pragma comment(lib, "AkGainFX.lib")
#		pragma message ("***WWISE linking against: AkVorbisDecoder.lib")
#		pragma comment(lib, "AkVorbisDecoder.lib")
#		pragma message ("***WWISE linking against: AkTimeStretchFX.lib")
#		pragma comment(lib, "AkTimeStretchFX.lib")
#		pragma message ("***WWISE linking against: AstoundsoundShared.lib")
#		pragma comment(lib, "AstoundsoundShared.lib")
#		pragma message ("***WWISE linking against: iZTrashFiltersFX.lib")
#		pragma comment(lib, "iZTrashFiltersFX.lib")
#		pragma message ("***WWISE linking against: AkMatrixReverbFX.lib")
#		pragma comment(lib, "AkMatrixReverbFX.lib")
#		pragma message ("***WWISE linking against: AkMeterFX.lib")
#		pragma comment(lib, "AkMeterFX.lib")
#		pragma message ("***WWISE linking against: AkHarmonizerFX.lib")
#		pragma comment(lib, "AkHarmonizerFX.lib")
#		pragma message ("***WWISE linking against: AkPeakLimiterFX.lib")
#		pragma comment(lib, "AkPeakLimiterFX.lib")
#		pragma message ("***WWISE linking against: AkExpanderFX.lib")
#		pragma comment(lib, "AkExpanderFX.lib")
#		pragma message ("***WWISE linking against: AuroHeadphoneFX.lib")
#		pragma comment(lib, "AuroHeadphoneFX.lib")
#		pragma message ("***WWISE linking against: AuroPannerMixer.lib")
#		pragma comment(lib, "AuroPannerMixer.lib")
#		pragma message ("***WWISE linking against: AkSynthOne.lib")
#		pragma comment(lib, "AkSynthOne.lib")
#		pragma message ("***WWISE linking against: IOSONOProximityMixer.lib")
#		pragma comment(lib, "IOSONOProximityMixer.lib")
#endif // WWISE_FOR_DEBUG || WWISE_FOR_PROFILE || WWISE_FOR_RELEASE
#endif // Win64

// XboxOne
//////////////////////////////////////////////////////////////////////////
#if defined(DURANGO)
#pragma message (">>> XboxOne:")
#include <xdk.h>

#if defined(WWISE_FOR_DEBUG) || defined(WWISE_FOR_PROFILE) || defined(WWISE_FOR_RELEASE)
// Core modules
#		pragma message ("***WWISE linking against: AkMemoryMgr.lib")
#		pragma comment(lib, "AkMemoryMgr.lib")
#		pragma message ("***WWISE linking against: AkMusicEngine.lib")
#		pragma comment(lib, "AkMusicEngine.lib")
#		pragma message ("***WWISE linking against: AkSoundEngine.lib")
#		pragma comment(lib, "AkSoundEngine.lib")
#		pragma message ("***WWISE linking against: AkStreamMgr.lib")
#		pragma comment(lib, "AkStreamMgr.lib")
#if !defined(WWISE_FOR_RELEASE)
// Does not exist for Release builds!
#		pragma message ("***WWISE linking against: CommunicationCentral.lib")
#		pragma comment(lib, "CommunicationCentral.lib")
#endif // !WWISE_FOR_RELEASE

// Plug-ins
#		pragma message ("***WWISE linking against: AkAudioInputSource.lib")
#		pragma comment(lib, "AkAudioInputSource.lib")
#		pragma message ("***WWISE linking against: AkCompressorFX.lib")
#		pragma comment(lib, "AkCompressorFX.lib")
#		pragma message ("***WWISE linking against: AkConvolutionReverbFX.lib")
#		pragma comment(lib, "AkConvolutionReverbFX.lib")
#		pragma message ("***WWISE linking against: AkDelayFX.lib")
#		pragma comment(lib, "AkDelayFX.lib")
#		pragma message ("***WWISE linking against: AkExpanderFX.lib")
#		pragma comment(lib, "AkExpanderFX.lib")
#		pragma message ("***WWISE linking against: AkFlangerFX.lib")
#		pragma comment(lib, "AkFlangerFX.lib")
#		pragma message ("***WWISE linking against: AkGainFX.lib")
#		pragma comment(lib, "AkGainFX.lib")
#		pragma message ("***WWISE linking against: AkGuitarDistortionFX.lib")
#		pragma comment(lib, "AkGuitarDistortionFX.lib")
#		pragma message ("***WWISE linking against: AkHarmonizerFX.lib")
#		pragma comment(lib, "AkHarmonizerFX.lib")
#		pragma message ("***WWISE linking against: AkMatrixReverbFX.lib")
#		pragma comment(lib, "AkMatrixReverbFX.lib")
#		pragma message ("***WWISE linking against: AkMeterFX.lib")
#		pragma comment(lib, "AkMeterFX.lib")
#		pragma message ("***WWISE linking against: AkMotionGenerator.lib")
#		pragma comment(lib, "AkMotionGenerator.lib")
#		pragma message ("***WWISE linking against: AkParametricEQFX.lib")
#		pragma comment(lib, "AkParametricEQFX.lib")
#		pragma message ("***WWISE linking against: AkPeakLimiterFX.lib")
#		pragma comment(lib, "AkPeakLimiterFX.lib")
#		pragma message ("***WWISE linking against: AkPitchShifterFX.lib")
#		pragma comment(lib, "AkPitchShifterFX.lib")
#		pragma message ("***WWISE linking against: AkRoomVerbFX.lib")
#		pragma comment(lib, "AkRoomVerbFX.lib")
#		pragma message ("***WWISE linking against: AkRumble.lib")
#		pragma comment(lib, "AkRumble.lib")
#		pragma message ("***WWISE linking against: AkSilenceSource.lib")
#		pragma comment(lib, "AkSilenceSource.lib")
#		pragma message ("***WWISE linking against: AkSineSource.lib")
#		pragma comment(lib, "AkSineSource.lib")
#		pragma message ("***WWISE linking against: AkSoundSeedImpactFX.lib")
#		pragma comment(lib, "AkSoundSeedImpactFX.lib")
#		pragma message ("***WWISE linking against: AkSoundSeedWind.lib")
#		pragma comment(lib, "AkSoundSeedWind.lib")
#		pragma message ("***WWISE linking against: AkSoundSeedWoosh.lib")
#		pragma comment(lib, "AkSoundSeedWoosh.lib")
#		pragma message ("***WWISE linking against: AkStereoDelayFX.lib")
#		pragma comment(lib, "AkStereoDelayFX.lib")
#		pragma message ("***WWISE linking against: AkSynthOne.lib")
#		pragma comment(lib, "AkSynthOne.lib")
#		pragma message ("***WWISE linking against: AkTimeStretchFX.lib")
#		pragma comment(lib, "AkTimeStretchFX.lib")
#		pragma message ("***WWISE linking against: AkToneSource.lib")
#		pragma comment(lib, "AkToneSource.lib")
#		pragma message ("***WWISE linking against: AkTremoloFX.lib")
#		pragma comment(lib, "AkTremoloFX.lib")
#		pragma message ("***WWISE linking against: AkVorbisDecoder.lib")
#		pragma comment(lib, "AkVorbisDecoder.lib")
#		pragma message ("***WWISE linking against: AstoundsoundExpanderFX.lib")
#		pragma comment(lib, "AstoundsoundExpanderFX.lib")
#		pragma message ("***WWISE linking against: AstoundsoundFolddownFX.lib")
#		pragma comment(lib, "AstoundsoundFolddownFX.lib")
#		pragma message ("***WWISE linking against: AstoundsoundRTIFX.lib")
#		pragma comment(lib, "AstoundsoundRTIFX.lib")
#		pragma message ("***WWISE linking against: AstoundsoundShared.lib")
#		pragma comment(lib, "AstoundsoundShared.lib")
#		pragma message ("***WWISE linking against: CrankcaseAudioREVModelPlayerFX.lib")
#		pragma comment(lib, "CrankcaseAudioREVModelPlayerFX.lib")
#		pragma message ("***WWISE linking against: iZHybridReverbFX.lib")
#		pragma comment(lib, "iZHybridReverbFX.lib")
#		pragma message ("***WWISE linking against: iZTrashBoxModelerFX.lib")
#		pragma comment(lib, "iZTrashBoxModelerFX.lib")
#		pragma message ("***WWISE linking against: iZTrashDelayFX.lib")
#		pragma comment(lib, "iZTrashDelayFX.lib")
#		pragma message ("***WWISE linking against: iZTrashDistortionFX.lib")
#		pragma comment(lib, "iZTrashDistortionFX.lib")
#		pragma message ("***WWISE linking against: iZTrashDynamicsFX.lib")
#		pragma comment(lib, "iZTrashDynamicsFX.lib")
#		pragma message ("***WWISE linking against: iZTrashFiltersFX.lib")
#		pragma comment(lib, "iZTrashFiltersFX.lib")
#		pragma message ("***WWISE linking against: iZTrashMultibandDistortionFX.lib")
#		pragma comment(lib, "iZTrashMultibandDistortionFX.lib")
#		pragma message ("***WWISE linking against: McDSPFutzBoxFX.lib")
#		pragma comment(lib, "McDSPFutzBoxFX.lib")
#		pragma message ("***WWISE linking against: McDSPLimiterFX.lib")
#		pragma comment(lib, "McDSPLimiterFX.lib")
#		pragma message ("***WWISE linking against: IOSONOProximityMixer.lib")
#		pragma comment(lib, "IOSONOProximityMixer.lib")
#endif // WWISE_FOR_DEBUG || WWISE_FOR_PROFILE || WWISE_FOR_RELEASE
#endif // XboxOne

// PS4
//////////////////////////////////////////////////////////////////////////
#if defined(ORBIS)
#pragma message (">>> PS4:")

#if defined(WWISE_FOR_DEBUG) || defined(WWISE_FOR_PROFILE) || defined(WWISE_FOR_RELEASE)
// Core modules
#		pragma message ("***WWISE linking against: libAkMusicEngine.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkMusicEngine.a")
#		pragma message ("***WWISE linking against: libAkSoundEngine.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkSoundEngine.a")
#		pragma message ("***WWISE linking against: libAkStreamMgr.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkStreamMgr.a")
#		pragma message ("***WWISE linking against: libAkMemoryMgr.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkMemoryMgr.a")
#if !defined(WWISE_FOR_RELEASE)
// Does not exist for Release builds!
#		pragma message ("***WWISE linking against: libCommunicationCentral.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libCommunicationCentral.a")
#endif // !WWISE_FOR_RELEASE


// Plug-ins
#		pragma message ("***WWISE linking against: libAkAudioInputSource.a")
#		pragma comment(lib,"Audio/AK/lib/ps4/profile/libAkAudioInputSource.a")
#		pragma message ("***WWISE linking against: libAkCompressorFX.a")
#		pragma comment(lib,"Audio/AK/lib/ps4/profile/libAkCompressorFX.a")
#		pragma message ("***WWISE linking against: libAkConvolutionReverbFX.a")
#		pragma comment(lib,"Audio/AK/lib/ps4/profile/libAkConvolutionReverbFX.a")
#		pragma message ("***WWISE linking against: libAkDelayFX.a")
#		pragma comment(lib,"Audio/AK/lib/ps4/profile/libAkDelayFX.a")
#		pragma message ("***WWISE linking against: libAkExpanderFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkExpanderFX.a")
#		pragma message ("***WWISE linking against: libAkFlangerFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkFlangerFX.a")
#		pragma message ("***WWISE linking against: libAkGainFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkGainFX.a")
#		pragma message ("***WWISE linking against: libAkGuitarDistortionFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkGuitarDistortionFX.a")
#		pragma message ("***WWISE linking against: libAkHarmonizerFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkHarmonizerFX.a")
#		pragma message ("***WWISE linking against: libAkMatrixReverbFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkMatrixReverbFX.a")
#		pragma message ("***WWISE linking against: libAkMeterFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkMeterFX.a")
#		pragma message ("***WWISE linking against: libAkMotionGenerator.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkMotionGenerator.a")
#		pragma message ("***WWISE linking against: libAkParametricEQFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkParametricEQFX.a")
#		pragma message ("***WWISE linking against: libAkPeakLimiterFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkPeakLimiterFX.a")
#		pragma message ("***WWISE linking against: libAkPitchShifterFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkPitchShifterFX.a")
#		pragma message ("***WWISE linking against: libAkRoomVerbFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkRoomVerbFX.a")
#		pragma message ("***WWISE linking against: libAkRumble.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkRumble.a")
#		pragma message ("***WWISE linking against: libAkSilenceSource.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkSilenceSource.a")
#		pragma message ("***WWISE linking against: libAkSineSource.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkSineSource.a")
#		pragma message ("***WWISE linking against: libAkSoundSeedImpactFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkSoundSeedImpactFX.a")
#		pragma message ("***WWISE linking against: libAkSoundSeedWind.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkSoundSeedWind.a")
#		pragma message ("***WWISE linking against: libAkSoundSeedWoosh.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkSoundSeedWoosh.a")
#		pragma message ("***WWISE linking against: libAkStereoDelayFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkStereoDelayFX.a")
#		pragma message ("***WWISE linking against: libAkTimeStretchFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkTimeStretchFX.a")
#		pragma message ("***WWISE linking against: libAkToneSource.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkToneSource.a")
#		pragma message ("***WWISE linking against: libAkTremoloFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkTremoloFX.a")
#		pragma message ("***WWISE linking against: libAkVorbisDecoder.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkVorbisDecoder.a")
#		pragma message ("***WWISE linking against: libAstoundsoundExpanderFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAstoundsoundExpanderFX.a")
#		pragma message ("***WWISE linking against: libAstoundsoundFolddownFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAstoundsoundFolddownFX.a")
#		pragma message ("***WWISE linking against: libAstoundsoundRTIFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAstoundsoundRTIFX.a")
#		pragma message ("***WWISE linking against: libAstoundsoundShared.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAstoundsoundShared.a")
#		pragma message ("***WWISE linking against: libCrankcaseAudioREVModelPlayerFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libCrankcaseAudioREVModelPlayerFX.a")
#		pragma message ("***WWISE linking against: libiZHybridReverbFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libiZHybridReverbFX.a")
#		pragma message ("***WWISE linking against: libiZTrashBoxModelerFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libiZTrashBoxModelerFX.a")
#		pragma message ("***WWISE linking against: libiZTrashDelayFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libiZTrashDelayFX.a")
#		pragma message ("***WWISE linking against: libiZTrashDistortionFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libiZTrashDistortionFX.a")
#		pragma message ("***WWISE linking against: libiZTrashDynamicsFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libiZTrashDynamicsFX.a")
#		pragma message ("***WWISE linking against: libiZTrashFiltersFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libiZTrashFiltersFX.a")
#		pragma message ("***WWISE linking against: libiZTrashMultibandDistortionFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libiZTrashMultibandDistortionFX.a")
#		pragma message ("***WWISE linking against: libMcDSPFutzBoxFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libMcDSPFutzBoxFX.a")
#		pragma message ("***WWISE linking against: libMcDSPLimiterFX.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libMcDSPLimiterFX.a")
#		pragma message ("***WWISE linking against: libAkSynthOne.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libAkSynthOne.a")
#		pragma message ("***WWISE linking against: libIOSONOProximityMixer.a")
#		pragma comment(lib, "Audio/AK/lib/ps4/profile/libIOSONOProximityMixer.a")
#endif // WWISE_FOR_DEBUG || WWISE_FOR_PROFILE || WWISE_FOR_RELEASE
#endif // PS4

