#############################################################################
## Crytek Source File
## Copyright (C) 2013, Crytek Studios
##
## Creator: Christopher Bolte
## Date: Oct 31, 2013
## Description: WAF  based build system
#############################################################################

def build(bld):

	bld.CryEngineModule( 
		target     = 'CryEntitySystem', 
		vs_filter  = 'CryEngine',		
		file_list  = 'cryentitysystem.waf_files', 

		pch        = 'stdafx.cpp', 
	)		
