#############################################################################
## Crytek Source File
## Copyright (C) 2013, Crytek Studios
##
## Creator: Christopher Bolte
## Date: Oct 31, 2013
## Description: WAF  based build system
#############################################################################

def build(bld):
	wwise_core_libs             = [ 'AkMemoryMgr', 'AkMusicEngine', 'AkSoundEngine', 'AkStreamMgr' ]

	wwise_plugins_libs          = [
		'AkAudioInputSource',
		'AkCompressorFX',
		'AkConvolutionReverbFX',
		'AkDelayFX',
		'AkExpanderFX',
		'AkFlangerFX',
		'AkGainFX',
		'AkGuitarDistortionFX',
		'AkHarmonizerFX',
		'AkMatrixReverbFX',
		'AkMeterFX',
		'AkParametricEQFX',
		'AkPeakLimiterFX',
		'AkPitchShifterFX',
		'AkRoomVerbFX',
		'AkSilenceSource',
		'AkSineSource',
		'AkSoundSeedImpactFX',
		'AkSoundSeedWind',
		'AkSoundSeedWoosh',
		'AkStereoDelayFX',
		'AkTimeStretchFX',
		'AkToneSource',
		'AkTremoloFX',
		'AkVorbisDecoder',
		'McDSPFutzBoxFX',
		'McDSPLimiterFX',
		'AkSynthOne'
	]

	wwise_astound_plugins_libs  = [ 'AstoundsoundExpanderFX', 'AstoundsoundRTIFX', 'AstoundsoundFolddownFX', ]
	wwise_extra_plugins_libs    = [
		'iZTrashBoxModelerFX',
		'iZTrashDistortionFX',
		'iZTrashDynamicsFX',
		'iZTrashDelayFX',
		'iZHybridReverbFX',
		'CrankcaseAudioREVModelPlayerFX',
		'iZTrashMultibandDistortionFX',
		'iZTrashFiltersFX',
		'AkMotionGenerator',
		'AkRumble',
		'IOSONOProximityMixer'
	]

	# CommunicationCentral must be the linked before other wwise libraries on gcc-based linkers
	comm_central_libs      = [ 'CommunicationCentral' ]

	common_wwise_libs           = wwise_core_libs + wwise_plugins_libs

	win_libs                    = [ 'Ole32', 'dxguid', 'ws2_32', 'Dsound', 'XINPUT9_1_0', 'Msacm32' ]
	win_wwise_libs              = wwise_extra_plugins_libs + wwise_astound_plugins_libs + [ 'AkMP3Source', 'AuroHeadphoneFX', 'AuroPannerMixer', 'AstoundsoundShared' ]
	win_release_libs            = common_wwise_libs + win_wwise_libs + win_libs
	win_non_release_libs        = comm_central_libs + win_release_libs + [ 'SFlib' ]



	linux_libs                  = [ 'SDL2', 'pthread' ]
	linux_release_libs          = common_wwise_libs + linux_libs
	linux_non_release_libs      = comm_central_libs + linux_release_libs

	darwin_wwise_libs           = wwise_astound_plugins_libs + [ 'AstoundsoundShared', 'AkAACDecoder' ]
	darwin_release_libs         = common_wwise_libs + darwin_wwise_libs
	darwin_non_release_libs     = comm_central_libs + darwin_release_libs

	wwise_android_libs          = wwise_astound_plugins_libs
	android_release_libs        = common_wwise_libs + wwise_android_libs
	android_non_release_libs    = comm_central_libs + android_release_libs

	bld.CryEngineModule(
		target      = 'CryAudioImplWwise',
		vs_filter   = 'CryEngine/Audio/Implementations',

		file_list   = 'audioimplwwise.waf_files',
		pch         = 'stdafx.cpp',

		includes = [ '../../Common', bld.CreateRootRelativePath('Code/SDKs/Audio') ],

		debug_defines        = 'WWISE_FOR_DEBUG',
		profile_defines      = 'WWISE_FOR_PROFILE',
		performance_defines  = 'WWISE_FOR_RELEASE',
		release_defines      = 'WWISE_FOR_RELEASE',

		win_debug_lib                   = win_non_release_libs,
		win_profile_lib                 = win_non_release_libs,
		win_performance_lib             = win_release_libs,
		win_release_lib                 = win_release_libs,
		win_x86_debug_libpath           = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/win32/debug/vc110'),
		win_x86_profile_libpath         = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/win32/profile/vc110'),
		win_x86_performance_libpath     = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/win32/release/vc110'),
		win_x86_release_libpath         = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/win32/release/vc110'),
		win_x64_debug_libpath           = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/x64/debug/vc110'),
		win_x64_profile_libpath         = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/x64/profile/vc110'),
		win_x64_performance_libpath     = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/x64/release/vc110'),
		win_x64_release_libpath         = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/x64/release/vc110'),



		linux_debug_lib                 = linux_non_release_libs,
		linux_profile_lib               = linux_non_release_libs,
		linux_performance_lib           = linux_release_libs,
		linux_release_lib               = linux_release_libs,
		linux_x64_libpath               = bld.CreateRootRelativePath('Code/SDKs/SDL2/lib/linux/'),
		linux_x64_debug_libpath         = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/linux/x64/debug'),
		linux_x64_profile_libpath       = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/linux/x64/profile'),
		linux_x64_release_libpath       = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/linux/x64/release'),
		linux_x64_performance_libpath   = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/linux/x64/release'),

		darwin_debug_lib                = darwin_non_release_libs,
		darwin_profile_lib              = darwin_non_release_libs,
		darwin_performance_lib          = darwin_release_libs,
		darwin_release_lib              = darwin_release_libs,
		darwin_framework                = [ 'CoreAudio', 'AudioUnit', 'AudioToolbox' ],
		darwin_x64_debug_libpath        = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/mac/x64/debug'),
		darwin_x64_profile_libpath      = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/mac/x64/profile'),
		darwin_x64_release_libpath      = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/mac/x64/release'),
		darwin_x64_performance_libpath  = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/mac/x64/release'),
	
		android_debug_lib               = android_non_release_libs,
		android_profile_lib             = android_non_release_libs,
		android_performance_lib         = android_release_libs,
		android_release_lib             = android_release_libs,
		android_arm_debug_libpath       = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/android/armeabi/debug/'),
		android_arm_profile_libpath     = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/android/armeabi/profile/'),
		android_arm_performance_libpath = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/android/armeabi/release/'),
		android_arm_release_libpath     = bld.CreateRootRelativePath('Code/SDKs/Audio/AK/lib/android/armeabi/release/'),	
		android_debug_linkflags         = [ "-Wl,--whole-archive", bld.CreateRootRelativePath("Code/SDKs/Audio/AK/lib/android/armeabi/debug/libAstoundsoundShared.a"), "-Wl,--no-whole-archive" ],
		android_profile_linkflags       = [ "-Wl,--whole-archive", bld.CreateRootRelativePath("Code/SDKs/Audio/AK/lib/android/armeabi/profile/libAstoundsoundShared.a"), "-Wl,--no-whole-archive" ],
		android_performance_linkflags   = [ "-Wl,--whole-archive", bld.CreateRootRelativePath("Code/SDKs/Audio/AK/lib/android/armeabi/release/libAstoundsoundShared.a"), "-Wl,--no-whole-archive" ],
		android_release_linkflags       = [ "-Wl,--whole-archive", bld.CreateRootRelativePath("Code/SDKs/Audio/AK/lib/android/armeabi/release/libAstoundsoundShared.a"), "-Wl,--no-whole-archive" ],
    )
